-- exercicio 1

CREATE TABLE produto(
    id_produto int primary key,
    nome varchar(50),
    preco number(26)
);

CREATE SEQUENCE seq_produto_id 
INCREMENT BY 1
START WITH 100
NOMAXVALUE
NOCYCLE;

INSERT INTO produto(id_produto, nome, preco)
VALUES(seq_produto_id.NEXTVAL, 'Produto 1', 50);

-- exercicio 2
-- a pseudocoluna NEXTVAL acesso o próximo valor de um id (que não está ocupado), sendo útil para adicionar algo novo, 
-- enquanto o CURRVAL acessa o valor atual de um id, sendo útil para sequencias que precisa acessa o ultimo valor para prosseguir

SELECT seq_produto_id.CURRVAL
FROM DUAL;

-- exercicio 3

CREATE SEQUENCE seq_faturamento
INCREMENT BY 1
START WITH 1
NOCYCLE
NOMAXVALUE;

ALTER SEQUENCE seq_faturamento RESTART WITH 1;

-- exercicio 4

CREATE TABLE pedidos (
    id_pedido NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 5000 INCREMENT BY 5) primary key,
    nome varchar(50)
);

-- exercicio 5

CREATE SEQUENCE seq_transacoes
INCREMENT BY 1
NOMAXVALUE
NO CACHE
NOCYCLE;

-- o cache funciona como um "checkpoint" do sistema, mante-lo em 0 (NOCACHE) faz com que o sistema fique lento
-- mas mante-lo em um valor alto significa que caso o sistema caia, significa que muitos dados podem ser perdidos

ALTER SEQUENCE seq_transacoes
INCREMENT BY 1
NOMAXVALUE
CACHE 20
NOCYCLE;


