-- exercicio 1

CREATE TABLE produtos(
    id_produto INT PRIMARY KEY,
    nome VARCHAR2(50),
    preco NUMBER(10,2)
);

CREATE SEQUENCE seq_produto_id
START WITH 100
INCREMENT BY 1
NOMAXVALUE
NOCYCLE;

INSERT INTO produtos (id_produto, nome, preco)
VALUES (seq_produto_id.NEXTVAL, 'Produto 1', 50.00);

-- exercicio 2
-- a pseudocoluna NEXTVAL gera e pega o proximo valor da sequencia (avanca o contador),
-- enquanto o CURRVAL apenas pega o valor atual que já foi gerado na sessao, sem avancar a sequencia

SELECT seq_produto_id.CURRVAL
FROM DUAL;

-- exercicio 3

CREATE SEQUENCE seq_faturamento
INCREMENT BY 1
START WITH 1
NOCYCLE
NOMAXVALUE;

ALTER SEQUENCE seq_faturamento RESTART WITH 1;

-- exercicio 4

CREATE TABLE pedidos (
    id_pedido NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 5000 INCREMENT BY 5) primary key,
    nome varchar(50)
);

-- exercicio 5

CREATE SEQUENCE seq_transacoes
INCREMENT BY 1
NOMAXVALUE
NOCACHE
NOCYCLE;

-- o cache guarda uma quantidade de numeros na memoria ram para nao precisar acessar o disco toda hora
-- o NOCACHE deixa lento porque força a gravar no disco a cada insert, gerando fila de espera no banco
-- se o sistema cair com CACHE, perde-se apenas os numeros guardados na ram (gera buracos/gaps na sequencia), mas nao dados da tabela

ALTER SEQUENCE seq_transacoes CACHE 50;


